new-window 'bash /usr/local/etc/confs/start-tf.sh'
set mouse on
set status off
set-option -g remain-on-exit on

# truecolor terminal, must be changed!
set -g default-terminal "screen-256color"
set-option -sa terminal-overrides ",alacritty*:Tc"

# first split is horizontally, tf and others, focus on left side
split-window -h -b -l 100 'python3 -m py.chat'

# split vertically into three parts, lowest first so that lines can mean the
# exact pane size
split-window -v -l 10 'echo "party" && bash'
select-pane -t 0
split-window -v -l 10 'echo "binds" && bash'

# # split top left into two horizontally
# select-pane -t 0
# split-window -h 'echo "mobinfo" && bash'

# split middle left into two horizontally
select-pane -t 1
split-window -h 'echo "status" && bash'

# set focus to main pane
select-pane -t 4
