new-window 'bash /usr/local/etc/start-tf.sh'
set mouse on
set status off
# first split is horizontally, tf and others, focus on left side
split-window -h -b -l 100 'echo "chat" && bash'
# split vertically into three parts, party first so that lines can mean the
# exact pane size
split-window -v -l 10 'echo "party" && bash'
select-pane -t 0
split-window -v -l 10 'echo "binds" && bash'
# split top left into two
select-pane -t 0
split-window -h 'echo "mobinfo" && bash'
# split middle left into two
select-pane -t 2
split-window -h 'echo "status" && bash'
# set focus to main pane
select-pane -t 5
